environment:
    type: "VisualGroundingEnv"
    name: VisualGrounding-v0

gamma: 0.99
lamda: 0.95
updates: 30000
save_interval: 500
epochs: 8
n_workers: 1
worker_steps: 50
n_mini_batch: 5
value_loss_coefficient: 0.2
hidden_layer_size: 256
max_grad_norm: 0.5
transformer:
    num_blocks: 2
    embed_dim: 256
    num_heads: 1
    memory_length: 32
    positional_encoding: "relative" # options: "" "relative" "learned"
    layer_norm: "pre" # options: "" "pre" "post"
    gtrxl: True
    gtrxl_bias: 0.0
learning_rate_schedule:
    initial: 3.0e-4
    final: 3.0e-5
    power: 1.0
    max_decay_steps: 30000
beta_schedule:
    initial: 0.001
    final: 0.0001
    power: 1.0
    max_decay_steps: 30000
clip_range_schedule:
    initial: 0.2
    final: 0.2
    power: 1.0
    max_decay_steps: 30000